baseurl = "https://alexd.ch/" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"
title = "Alexander Döring"
theme = "academic"
enableRobotsTXT = true

sharing = true

[params]
  name = "Alexander Döring"
  role = "Senior Software Developer"
  organization = "smallpdf.com"
  organization_url = "https://smallpdf.com"
  avatar = "alexander.png"
  email = "email@alexd.ch"

[[params.social]]
  icon = "envelope"
  icon_pack = "fa"
  link = "mailto:email@alexd.ch"

[[params.social]]
  icon = "github"
  icon_pack = "fa"
  link = "//github.com/alexd765"

[[menu.main]]
    name = "Blog"
    url = "#posts"
    weight = 1

[[menu.main]]
    name = "About"
    url = "#about"
    weight = 2
